// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTq-5oM1bGzbaVz-5dKVsQ0zHcTW_WC4',
    appId: '1:209029797188:web:ecdd5f271fbb69dd697311',
    messagingSenderId: '209029797188',
    projectId: 'eduhub-cloud-db',
    authDomain: 'eduhub-cloud-db.firebaseapp.com',
    storageBucket: 'eduhub-cloud-db.firebasestorage.app',
    measurementId: 'G-SK5YGJJYG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bFdYksDcSot81HGPNMAzSKz4wf7IZNU',
    appId: '1:209029797188:android:38e347d04a9f9b40697311',
    messagingSenderId: '209029797188',
    projectId: 'eduhub-cloud-db',
    storageBucket: 'eduhub-cloud-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuTq-5oM1bGzbaVz-5dKVsQ0zHcTW_WC4',
    appId: '1:209029797188:web:2753eb90187b5385697311',
    messagingSenderId: '209029797188',
    projectId: 'eduhub-cloud-db',
    authDomain: 'eduhub-cloud-db.firebaseapp.com',
    storageBucket: 'eduhub-cloud-db.firebasestorage.app',
    measurementId: 'G-Y2NXGM8Y2M',
  );
}
